name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to shinyapps.io
      uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
      with:
        shinyapps-token: ${{ secrets.SHINYAPPS_TOKEN }}
