name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

  # run on request (via button in actions menu)
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to shinyapps

    
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: DeeNA95/shinyapps-deploy-github-action@v1.11
        with:
          appName: TYCL_Analysis
          forceUpdate: true
          accountName: deena95
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
